// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0T--08GYsMzg_CRfmQJpTcxWuBwOMjsU',
    appId: '1:953544959425:web:d6aafb2bfd1238c001fb40',
    messagingSenderId: '953544959425',
    projectId: 'bottleback-4e329',
    authDomain: 'bottleback-4e329.firebaseapp.com',
    storageBucket: 'bottleback-4e329.firebasestorage.app',
    measurementId: 'G-SFBSHBD3JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9KGnlRFQm8jJPv6jeZwLOICgc3_DbPWw',
    appId: '1:953544959425:android:848cdf69d7e93d4701fb40',
    messagingSenderId: '953544959425',
    projectId: 'bottleback-4e329',
    storageBucket: 'bottleback-4e329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGC9TPzofSaWIj3IKZvxte0m5dqsdwyG8',
    appId: '1:953544959425:ios:b2b62ae1882aa83e01fb40',
    messagingSenderId: '953544959425',
    projectId: 'bottleback-4e329',
    storageBucket: 'bottleback-4e329.firebasestorage.app',
    iosBundleId: 'com.example.bottlebackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGC9TPzofSaWIj3IKZvxte0m5dqsdwyG8',
    appId: '1:953544959425:ios:b2b62ae1882aa83e01fb40',
    messagingSenderId: '953544959425',
    projectId: 'bottleback-4e329',
    storageBucket: 'bottleback-4e329.firebasestorage.app',
    iosBundleId: 'com.example.bottlebackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0T--08GYsMzg_CRfmQJpTcxWuBwOMjsU',
    appId: '1:953544959425:web:b453992d8f931f9001fb40',
    messagingSenderId: '953544959425',
    projectId: 'bottleback-4e329',
    authDomain: 'bottleback-4e329.firebaseapp.com',
    storageBucket: 'bottleback-4e329.firebasestorage.app',
    measurementId: 'G-1CH55358K0',
  );
}
